### PR TITLE
Unroll exponentiation expressions during code generation

### LINKED ISSUE #130: unroll exponentiation into multiplications in winter codegen
We should remember that using `exp` could be quite expensive as it uses constant-time exponentiation. In the future, we might want o "unroll" this into a sequence of multiplications.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/air-script/pull/126#discussion_r1090953576_

### PR DESCRIPTION
**Pull request by jjcnn**
Fixes #130.

Exponentiation expressions are now unrolled during code generation for better performance.

### CODE REVIEW

**Comment by bobbinth** [comment]
I only looked at this briefly - so, might have missed something.

I think using a simple chain of multiplications would not give us the best result. For example, $x^7$ would require 7 multiplications while we can compute it using only 4 multiplications as:
```
fn exp7(a):
  let a2 = a * a;
  let a4 = a2 * a2;
  let a3 = a2 * a;
  return a3 * a4;
```

**Comment by jjcnn** [comment]
Ah, yes - that's what was meant by linear exponentiation in #130.

Your suggestion can only be implemented by introducing fresh variables in the generated code, and I don't know how to do that. I can try to figure it out if you think it's worth my time?

Another thing I don't know is how to test the implementation. None of our current tests have exponents greater than 3, and that would lead to the same number of multiplications as without the rewrite.

**Comment by bobbinth** [comment]
> Your suggestion can only be implemented by introducing fresh variables in the generated code, and I don't know how to do that. I can try to figure it out if you think it's worth my time?

I'd probably create a set of functions for exponentiation where the exponent is greater than 3 - e.g., `exp4`, `exp5` etc. Not sure how easy it would be to create a set of these functions dynamically - so, we can even consider pre-creating some set of them. We can probably safely assume that the exponent is not going be greater than 32 or something like that (for Miden, the exponent will never be greater than 9).

> Another thing I don't know is how to test the implementation. None of our current tests have exponents greater than 3, and that would lead to the same number of multiplications as without the rewrite.

If we don't have them already, we should soon write constraints for the ROP hash function. These would have exponentiation to power 7.

**Comment by tohrnii** [comment]
Question: Can't we generalize this with something like:

```
fn pow<E: FieldElement<BaseField = Felt>>(base: E, exp: u64) -> E {
    if exp == 1 {
        return base;
    } else if exp % 2 == 0 {
        let result = pow(base, exp / 2);
        return result * result;
    } else {
        let result = pow(base, (exp - 1)/2);
        return base * result * result;
    }
}
```
or am I missing something?

**Comment by bobbinth** [comment]
@tohrnii - we can't use conditional statements or `%` operation when computing AIR constraints. We can use only field operations (or statements which reduce to field operations).

**Comment by tohrnii** [comment]
@bobbinth - Ah, got it. Thanks.

**Comment by bobbinth** [comment]
Superseded by #333.

**Pull request closed without merging**
