### PR TITLE
refactor IR tests

### PR DESCRIPTION
**Pull request by grjte**
This PR includes a trivial clippy fix and a quick refactor to split the IR tests into modules to make them more manageable and easier to update later. This addresses #138

### CODE REVIEW

**Review by tohrnii — APPROVED** [review]
Thank you @grjte, looks good to me. One question is if we should replace `boundary_constraints` and `integrity_constraints` in function names to their abbreviated forms (`bc` and `ic`) to be consistent except for `boundary_constraints()` and `integrity_constraints()`? If you agree with this change maybe it can be done with this PR?

**Comment by grjte** [comment]
> Thank you @grjte, looks good to me. One question is if we should replace `boundary_constraints` and `integrity_constraints` in function names to their abbreviated forms (`bc` and `ic`) to be consistent except for `boundary_constraints()` and `integrity_constraints()`? If you agree with this change maybe it can be done with this PR?

Do you mean the accessor functions? I would probably leave them as it is and keep this PR as a tests refactor

**Comment by tohrnii** [comment]
No I actually meant just for test names. For eg, renaming `boundary_constraints_with_constants` to `bc_with_constants` etc.

**Comment by grjte** [comment]
> No I actually meant just for test names. For eg, renaming `boundary_constraints_with_constants` to `bc_with_constants` etc.

Ah, I see. The way I had done it was to shorten it in the error case and leave it unshortened for the main test, but I don't feel strongly. I've changed it in all cases except when there's nothing else in the name (e.g. `boundary_constraints`)

**Pull request merged**
