### PR TITLE
Fix doc rendering issue

### PR DESCRIPTION
**Pull request by tohrnii**
Addressing #78.

### CODE REVIEW

**Review by grjte — CHANGES_REQUESTED** [review]
This fixes look good to me! However, the mdbook only deploys from main. We should probably do one of the following:

1. keep docs in sync with next, and change the CI `book.yml` workflow to deploy when the `next` branch is updated
2. merge this to `main` instead and then rebase `next`

I think this project is young enough and fast-moving enough that I'd probably go for the first option. What do you think?

**Comment by tohrnii** [comment]
@grjte Agreed! I made the change to `book.yml`.

**Comment by Al-Kindi-0** [comment]
Thank you @tohrnii ! 
A couple of questions: 

1. Is \$rand the correct syntax or is it $rand and \$ is just for .md formatting?
2. Does this address the issue in the example in section 2.5?

**Comment by tohrnii** [comment]
@Al-Kindi-0 To answer your questions:
1. It's just for .md formatting. The correct syntax in AirScript is without the back slash.
2. The fix for that was included in https://github.com/0xPolygonMiden/air-script/pull/74 however it may not be getting reflected right now since the change was made to `next` branch but the docs are being pulled from `main` branch. That has been fixed in this PR so should be fixed after this PR is merged.

**Comment by Al-Kindi-0** [comment]
Thank you!
In line 91, should that be "last row" instead?

**Comment by tohrnii** [comment]
@Al-Kindi-0 Thank you. Fixed.

**Review by Al-Kindi-0 — APPROVED** [review]

**Review by grjte — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
