### PR TITLE
Add parens based on operator precedence

### PR DESCRIPTION
**Pull request by tohrnii**
This PR adds a fix for the redundant parentheses in expressions. Here we check the precedence between the two operands and only add parentheses when the operand precedence is lower.

### CODE REVIEW

**Review by Overcastan — APPROVED** [review]
Looks good to me, thank you @tohrnii !

**Comment by tohrnii** [comment]
One question here is how should we handle `Exp` operation. Should the base always have parentheses or only non-leaf expressions have them.

**Review by Al-Kindi-0 — APPROVED** [review]
Looks good, thank you!

**Comment by grjte** [comment]
> One question here is how should we handle `Exp` operation. Should the base always have parentheses or only non-leaf expressions should have them.

Ideally, parentheses should only be there in cases where they're syntactically necessary for the correctness of the calculation

**Comment by tohrnii** [comment]
> Ideally, parentheses should only be there in cases where they're syntactically necessary for the correctness of the calculation.

> However, it's not worth spending a lot of time on this right now, so the simplest solution is fine.

Makes sense. I've skipped it for now since it requires either introducing a little redundancy or making the helper function slightly more complicated so just went with keeping it simple for now.

**Comment by tohrnii** [comment]
Superseded by #155

**Pull request closed without merging**
